#!/bin/bash
# ══════════════════════════════════════════════════════════════
# Script d'installation — Sevenz Proxy Server
# Usage : curl -fsSL https://raw.githubusercontent.com/nina7t/Seven/main/server/install.sh | bash
# ══════════════════════════════════════════════════════════════

set -e

echo "🚀 Sevenz Proxy — Installation sur Oracle Cloud"
echo "================================================"

# ─── Couleurs ───
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

info()    { echo -e "${GREEN}[INFO]${NC} $1"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $1"; }
error()   { echo -e "${RED}[ERROR]${NC} $1"; exit 1; }

# ─── Vérifications ───
if [ "$(id -u)" -eq 0 ]; then
  warn "Exécution en root détectée — création de l'utilisateur ubuntu si nécessaire..."
  if ! id -u ubuntu &>/dev/null; then
    useradd -m -s /bin/bash ubuntu
    mkdir -p /home/ubuntu/.ssh
    cp /root/.ssh/authorized_keys /home/ubuntu/.ssh/ 2>/dev/null || true
    chown -R ubuntu:ubuntu /home/ubuntu/.ssh
    echo "ubuntu ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers.d/ubuntu
    chmod 440 /etc/sudoers.d/ubuntu
  fi
  RUN_AS="sudo -u ubuntu"
else
  RUN_AS="bash"
fi

# ─── Mise à jour système ───
info "Mise à jour du système..."
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get upgrade -y

# ─── Node.js 20 LTS ───
info "Installation Node.js 20..."
curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
apt-get install -y nodejs
node --version
npm --version

# ─── Python + yt-dlp + ffmpeg ───
info "Installation yt-dlp, ffmpeg et dépendances..."
apt-get install -y python3 python3-pip ffmpeg curl wget

# yt-dlp (latest version via pip)
pip3 install yt-dlp --break-system-packages --quiet

# Vérification yt-dlp
YTDLP_VERSION=$(yt-dlp --version 2>/dev/null || echo "ERREUR")
info "yt-dlp version: $YTDLP_VERSION"

# ─── pm2 ───
info "Installation pm2..."
npm install -g pm2
pm2 --version

# ─── UFW Firewall ───
info "Configuration du firewall..."
apt-get install -y ufw
ufw --force default allow outgoing
ufw --force default deny incoming
ufw allow 22/tcp comment 'SSH'
ufw allow 3001/tcp comment 'Sevenz Proxy'
ufw --force enable
ufw status | grep -E "3001|22"

# ─── Créer le dossier de l'app ───
info "Création du dossier /opt/sevenz-proxy..."
mkdir -p /opt/sevenz-proxy
chown -R $(whoami):$(whoami) /opt/sevenz-proxy

# ─── Script de conversion cookies ───
info "Création du script de conversion cookies..."
cat > /opt/sevenz-proxy/convert_cookies.py << 'PYEOF'
#!/usr/bin/env python3
"""Convertit les cookies EditThisCookie (JSON) en format Netscape cookies.txt"""
import sys
import json

if len(sys.argv) < 2:
    print("Usage: python3 convert_cookies.py <fichier_cookies_json> [output_netscape.txt]")
    sys.exit(1)

input_file = sys.argv[1]
output_file = sys.argv[2] if len(sys.argv) > 2 else "cookies.txt"

try:
    with open(input_file, 'r') as f:
        cookies = json.load(f)
except json.JSONDecodeError:
    print(f"Erreur: {input_file} n'est pas un JSON valide")
    sys.exit(1)

lines = ["# Netscape HTTP Cookie File", "# This file was generated by EditThisCookie -> convert_cookies.py"]

for c in cookies:
    domain = c.get("domain", ".youtube.com")
    if domain.startswith("."):
        domain_flag = "TRUE"
        domain = domain[1:]
    else:
        domain_flag = "FALSE"
    
    secure = "TRUE" if c.get("secure", False) else "FALSE"
    expires = int(c.get("expirationDate", 0))
    path = c.get("path", "/")
    name = c.get("name", "")
    value = c.get("value", "")
    
    lines.append(f"{domain}\t{domain_flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}")

with open(output_file, 'w') as f:
    f.write('\n'.join(lines) + '\n')

print(f"✓ {len(cookies)} cookies exportés vers {output_file}")
PYEOF
chmod +x /opt/sevenz-proxy/convert_cookies.py

# ─── Script de démarrage automatique ───
info "Configuration pm2 au démarrage..."
$RUN_AS << 'RUNAS'
cd /opt/sevenz-proxy
pm2 start server.js --name sevenz 2>/dev/null || true
pm2 save 2>/dev/null || true
RUNAS

# ─── Résumé ───
echo ""
echo "================================================"
echo "✅ Installation terminée !"
echo "================================================"
echo ""
echo "📁 Dossier de l'app : /opt/sevenz-proxy"
echo "🔒 Firewall : ports 22 (SSH) et 3001 ouverts"
echo "📦 pm2 : actif et configured pour démarrage auto"
echo ""
echo "Prochaines étapes :"
echo "  1. Transfère ton code server.js vers /opt/sevenz-proxy/"
echo "  2. Ajoute le fichier cookies.txt (format Netscape)"
echo "  3. Crée le fichier .env avec tes clés API"
echo "  4. npm install (dans /opt/sevenz-proxy)"
echo "  5. pm2 restart sevenz"
echo ""
echo "Test : curl http://localhost:3001/api/health"
echo "================================================"